name: Main Branch CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    uses: ./.github/workflows/build.yml

  test-matrix:
    needs: build
    strategy:
      matrix:
        python-version: ['3.9', '3.10', '3.11', '3.12', '3.13']
    uses: ./.github/workflows/test.yml
    with:
      python-version: ${{ matrix.python-version }}
      upload-coverage: ${{ matrix.python-version == '3.9' }}
