name: Publish Package

on:
  release:
    types: [created]
  workflow_dispatch:

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  build:
    uses: ./.github/workflows/build.yml

  test:
    needs: build
    uses: ./.github/workflows/test.yml
    with:
      python-version: '3.10'
      upload-coverage: true

  publish-docker:
    needs: [build, test]
    uses: ./.github/workflows/publish-docker.yml
    with:
      image_tag: ${{ github.event_name == 'release' && github.ref_name || 'latest' }}
    secrets: inherit
