name: Pull Request Checks

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    uses: ./.github/workflows/build.yml

  test:
    needs: build
    uses: ./.github/workflows/test.yml
    with:
      python-version: '3.9'
      upload-coverage: true
