name: Update Version Badge

on:
  push:
    branches:
      - main
    paths:
      - 'pyproject.toml'
  workflow_dispatch:  # Allow manual triggering

jobs:
  update-badge:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tomli

      - name: Extract version from pyproject.toml
        id: get_version
        run: |
          VERSION=$(python -c "import tomli; print(tomli.load(open('pyproject.toml', 'rb'))['project']['version'])")
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "Version: $VERSION"

      - name: Generate badge JSON
        run: |
          mkdir -p .github/badges
          cat > .github/badges/version.json << EOF
          {
            "schemaVersion": 1,
            "label": "version",
            "message": "${{ env.VERSION }}",
            "color": "green"
          }
          EOF

      - name: Commit and push badge
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .github/badges/version.json
          git commit -m "Update version badge to ${{ env.VERSION }}" || echo "No changes to commit"
          git push
